name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Starting server for curl test
      run: nohup ./target/debug/multiproxy https://www.rust-lang.org/ https://hmpioneers.net/hockey/ &
    - name: Get content from 1st website
      run: curl -f -s "http://0.0.0.0:8888/learn" | grep "Rust"
    - name: Get content from 2nd website
      run: curl -f -s "http://0.0.0.0:8888/history.htm" | grep "Hill-Murray"
